twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        tiny_mce_api_key: '%env(TINY_MCE_API_KEY)%'

when@test:
    twig:
        strict_variables: true
